name: Snyk OSS Gating Check (only fixables)

on:
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk OSS scan and save output
        run: snyk test --all-projects --json > snyk-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - - name: Fail only on fixable high/critical vulnerabilities
  run: |
    node -e "
    const fs = require('fs');
    const data = JSON.parse(fs.readFileSync('snyk-results.json', 'utf8'));
    const projects = Array.isArray(data) ? data : [data];
    let fail = false;
    const matched = [];

    for (const proj of projects) {
      const manifest = proj.displayTargetFile || proj.targetFile || proj.projectName || 'unknown';
      for (const v of proj.vulnerabilities || []) {
        const isFixable = v.isUpgradable || v.isPatchable || (v.fixedIn && v.fixedIn.length > 0);
        if (['high', 'critical'].includes(v.severity) && isFixable) {
          matched.push({
            severity: v.severity,
            package: v.packageName,
            version: v.version,
            fixedIn: v.fixedIn?.join(', ') || 'N/A',
            title: v.title || '',
            manifest
          });
          fail = true;
        }
      }
    }

    if (fail) {
      console.error('⛔ Gating failed due to the following fixable high/critical vulnerabilities:\n');
      matched.forEach(vuln => {
        console.error(\`🔴 [\${vuln.severity.toUpperCase()}] \${vuln.package}@\${vuln.version} (\${vuln.title})\n     Manifest: \${vuln.manifest}\n     Fix Available: \${vuln.fixedIn}\n\`);
      });
      console.error(\`Total: \${matched.length} fixable high/critical vulnerabilities\n\`);
      process.exit(1);
    } else {
      console.log('✅ No fixable high/critical vulnerabilities found.');
    }
    "
